export enum Resource {
  Organizations = 'organizations',
  Dashboard = 'dashboard',
  Dzent = 'dzent',
  Users = 'users',
  CampaignManagement = 'campaignManagement',
  Clients = 'clients',
  Campaigns = 'campaigns',
  LineItems = 'lineItems',
  Leads = 'leads',
  IntegrationHub = 'integrationHub',
  Integrations = 'integrations',
  Templates = 'templates',
  LeadValidationSettings = 'lead-validation-settings',
  AdminConsole = 'adminConsole',
  RolesAndPermissions = 'rolesAndPermissions',
  Analytics = 'analytics',
  Marketers = 'Marketers',
  Supplier = 'Supplier',
  SearchData = 'searchData',
  SearchDatabase = 'searchDatabase',
  ConnectPlatforms = 'connectPlatforms',
  Pixels = 'pixels',
  Jobs = 'jobs',
}
